#特别注意：下面这些与spring-cloud相关的属性必须配置在bootstrap.properties中，
#config部分内容才能被正确加载。因为config的相关配置会先于application.properties，
#而bootstrap.properties的加载也是先于application.properties。
server:
  port: 8810
  time: 1234
spring:
  application:
    name: config-client

spring:
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪
  rabbitmq:
    host: localhost #rabbitMQ 服务ip
    port: 5672 #rabbitMQ 服务端口号
    username: guest #rabbitMQ 服务用户名
    password: guest #rabbitMQ 服务密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #指向配置中心的地址
